### PR TITLE
Implement A2B10G10R10 TextureFormat

### PR DESCRIPTION
**Pull request by greggameplayer**

### CODE REVIEW

**Comment by Dantttt** [comment]
I don't have errors with your PR and SMO go in game now

**Comment by AcK77** [comment]
"Go in game"? How is that possible without shaders?

**Comment by Dantttt** [comment]
You can't play but if you build this PR with docked mode you can go in game

**Comment by AcK77** [comment]
Screenshot?

**Comment by ReaperOfSouls1909** [comment]
unknown

**Comment by Dantttt** [comment]
I'll leave it on a DM in your profile in discord,i can't send it here somehow

**Comment by AcK77** [comment]
That’s not really what I call "In game" but well there is progression!

**Comment by ReaperOfSouls1909** [comment]
well as it is in game and thats the pause menu thats as in game as it gets ya know

**Comment by AcK77** [comment]
As I said, there is progression in the execution of SMO, but at least I can’t see any game on the screenshot since shaders instructions are not implemented! It’s just, execution progression... Anyway, thanks for the feedback!

**Comment by Margen67** [comment]
@AcK77 Just because you can't see anything doesn't mean it's not ingame.

**Comment by ReinUsesLisp** [comment]
The following C code outputs blue:
```
	int alpha = 3;
	int blue  = 0;
	int green = 0;
	int red   = 1023;

	int color = alpha | (blue << 2) | (green << 12) | (red << 22);

	GLuint texid;
	glGenTextures(1, &texid);

	glBindTexture(GL_TEXTURE_2D, texid);
	glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, 1, 1, 0, GL_RGBA, GL_UNSIGNED_INT_2_10_10_10_REV, &color);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
```
If data is sent in a format like `color` is built, then type musn't be reversed.

**Comment by greggameplayer** [comment]
If I have to i will reopen a PR for that because i can't modifie this because i have delete my fork and refork this repo

**Comment by ReinUsesLisp** [comment]
Leave as it is for now. I'd like to write some homebrew mesa tests before merging. We can't really tell if it's with or without reverse since SMO is showing a black screen (for other reasons).

**Comment by greggameplayer** [comment]
Will Reopen a new PR in order to correct Conflicts

**Pull request closed without merging**
