### PR TITLE
Add & Correct ErrorModules

### PR DESCRIPTION
**Pull request by greggameplayer**
These changes have been made according to : 
http://switchbrew.org/index.php?title=Error_codes

### CODE REVIEW

**Comment by gdkchan** [comment]
While you're at it, can you also remove the libnx specific error codes?

**Comment by greggameplayer** [comment]
@gdkchan Ok, i do that.

**Comment by greggameplayer** [comment]
@gdkchan like this ?

**Comment by gdkchan** [comment]
Also Homebrew_ABI/Homebrew_Loader.

**Comment by greggameplayer** [comment]
Ok

**Comment by greggameplayer** [comment]
@gdkchan It's done

**Comment by gdkchan** [comment]
lgtm, thanks!

**Pull request merged**
