### PR TITLE
Implement GetAvailableLanguageCodeCount2

### PR DESCRIPTION
**Pull request by greggameplayer**
according to switchbrew GetAvailableLanguageCodeCount and GetAvailableLanguageCodeCount2 are the same.

### CODE REVIEW

**Comment by AcK77** [comment]
« GetAvailableLanguageCodes2/GetAvailableLanguageCodeCount2 instead of {original commands}.
In official user-processes in the #Language->#LanguageCode conversion function (MakeLanguageCode):
During one-time init, GetAvailableLanguageCodes is used to initialize the LanguageCodes array cache, with max_entries=0xF (buffer size in u64s). [4.0.0+] GetAvailableLanguageCodes2 is now used with max_entries 0x40.
[4.0.0+] When the input #Language is larger than the cached total_entries from the above command output, or #Language is negative, command MakeLanguageCode is used instead of the array. » I don’t thinks it’s really the same method... Some investigation is required!

**Comment by greggameplayer** [comment]
@AcK77 yes but for now we don't know much more on this function. maybe GetAvailableLanguageCodeCount2 is used for GetAvailableLanguageCodes2 and GetAvailableLanguageCodeCount is used for GetAvailableLanguageCodes. I think these two functions just don't return the same value.

**Comment by AcK77** [comment]
As I said, switchbrew docs explained how it works:

```
[4.0.0+] Official user-processes now use GetAvailableLanguageCodes2/GetAvailableLanguageCodeCount2 instead of {original commands}.

In official user-processes in the #Language->#LanguageCode conversion function (MakeLanguageCode):

During one-time init, GetAvailableLanguageCodes is used to initialize the LanguageCodes array cache, with max_entries=0xF (buffer size in u64s). [4.0.0+] GetAvailableLanguageCodes2 is now used with max_entries 0x40.
[4.0.0+] When the input #Language is larger than the cached total_entries from the above command output, or #Language is negative, command MakeLanguageCode is used instead of the array.
```

So it's not the same methods... All you did here is to copy paste some code and not implement the real method. You are free to update it if you can, or close this PR if you can't. Thanks.

**Comment by greggameplayer** [comment]
I close this PR until we find a proper way to implement it

**Pull request closed without merging**
