### PR TITLE
[WIP] Experimental basic XInput support.

### PR DESCRIPTION
**Pull request by Cyuubi**
Title says it all, this is experimental and probably doesn't work on Linux. Both left and right joysticks aren't implemented (though they will be soon) and eventually I'll add support for changing the keybinds in config.

### CODE REVIEW

**Comment by zoltx23** [comment]
I will see if I can test the inputs in my Xbox one controller tomorrow. Maybe also experiment with the Joystick and Trigger inputs as well.

**Comment by Cyuubi** [comment]
Joystick and triggers aren't added.

**Comment by zoltx23** [comment]
Well, I knew that much. I meant more so try and implement them if I can. Since it seems you are using another library for Xinput.

**Comment by gdkchan** [comment]
The way you handle button presses looks wrong. Based on the name I'm pretty sure that the button values are suppsoed to be used as flags, but instead you use it with a switch. The end result is that if you press multiple buttons at once on the controller, only one will be detected.

**Comment by Cyuubi** [comment]
Added more buttons and fixed multiple inputs at the same time.

**Comment by Cyuubi** [comment]
Added XInput config

**Comment by Luffykun007** [comment]
@Cyuubi Having this error now, soon after the emulator close.

capturar

**Comment by Cyuubi** [comment]
Fixed, my bad.

**Comment by gdkchan** [comment]
Was this tested on linux? I don't think you can use XInput there as DirectX is windows only.

**Comment by Cyuubi** [comment]
Yeah, if someone wants to test this on Linux (to see if it crashes), please do!

**Comment by DrHacknik** [comment]
I am assuming Ryujinx works in Solus. So I'll try~

**Comment by ReinUsesLisp** [comment]
On Arch Linux (no extra packages were installed):
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'SharpDX.XInput.Controller' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'kernel32' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32: cannot open shared object file: No such file or directory
   at SharpDX.XInput.Controller.LoadLibrary(String lpFileName)
   at SharpDX.XInput.Controller..cctor()
   --- End of inner exception stack trace ---
   at SharpDX.XInput.Controller..ctor(UserIndex userIndex)
   at Ryujinx.GLScreen..ctor(Switch Ns, IGalRenderer Renderer) in Ryujinx-Cyuubi/Ryujinx/Ui/GLScreen.cs:line 25
   at Ryujinx.Program.Main(String[] args) in Ryujinx-Cyuubi/Ryujinx/Ui/Program.cs:line 63
```
Tried installing wine (in case it magically brought the dependency) without luck.

I think that conditionally initializing XInput on Windows might be a solution.

**Comment by Cyuubi** [comment]
Closing because #196 is merged and better than this.

**Pull request closed without merging**
