### PR TITLE
Add an ASTC Decoder (Not currently used in Ryujinx)

### PR DESCRIPTION
**Pull request by AcK77**

### CODE REVIEW

**Comment by RyuDanuer** [comment]
what does ASTC Decoder do?

**Comment by AcK77** [comment]
Well... Decode ASTC I guess ?

**Comment by firewolfgames** [comment]
It decodes the ASTC texture format, used by Super Mario Odyssey (and most likely other games as well)

**Comment by gdkchan** [comment]
lgtm, thanks!

**Pull request merged**
