### PR TITLE
minimal gui

### PR DESCRIPTION
**Pull request by NekokoTime**

### CODE REVIEW

**Comment by emmauss** [comment]
Please stop this. It is not ready yet.

**Comment by Luffykun007** [comment]
This is his channel on You tube for those who want to praise him there.
it also has an account with the channel name of it @Emulation Channel.

https://www.youtube.com/watch?v=VqFbAue20EM

**Comment by Cyuubi** [comment]
we dont praise him, we hate him lol.

**Comment by Luffykun007** [comment]
I was being sarcastic of course we hated him.

**Comment by Cyuubi** [comment]
ah alright

**Comment by Luffykun007** [comment]
here is proof see the files on your desktop in this photo in a PR fo yuzu and now watch his latest video and draw your own conclusions.

https://github.com/yuzu-emu/yuzu/pull/562

**Comment by AcK77** [comment]
Subject close. Thanks.

**Pull request closed without merging**
